CREATE TABLE `data_insert` (  
  `id` int(11) NOT NULL,  
  `CompanyName` varchar(100) NOT NULL,  
  `CompanyEmail` varchar(150) NOT NULL,
  `Item` varchar(30) NOT NULL,
  `ExpDate` varchar(30) NOT NULL,
  `Message` varchar(100) NOT NULL,
  `image` varchar(200) NOT NULL.
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
